# Server config
server:
  port: ${PORT:8888}

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

info:
  component: API Gateway

# Spring config
spring:
  application:
    name: api-gateway

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registerWithEureka: true

# Ribbon config
ribbon:
  eureka:
    enabled: true

# Zuul config
zuul:
  prefix: /api
  routes:
    patients:
      path: /patients/**
      serviceId: patient-service
    units:
      path: /units/**
      serviceId: unit-service
    admissions:
      path: /admissions/**
      serviceId: admission-service
    equipments:
      path: /equipments/**
      serviceId: equipment-service

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false