INSERT INTO TBL_PROFILE(id, first_name, middle_name, last_name, birthdate, gender, address, phone, email) VALUES (1, 'Tony', 'Touma', 'Tannoury', '1990-01-14T21:32:29', 'M', 'Beirut', '03427586', 'tony.touma@hotmail.com');
INSERT INTO TBL_PROFILE(id, first_name, middle_name, last_name, birthdate, gender, address, phone, email) VALUES (2, 'William', 'Constatine', 'Haber', '1992-06-18T21:32:29', 'M', 'Tikrit', '03495186', 'william@gmail.com');
INSERT INTO TBL_PROFILE(id, first_name, middle_name, last_name, birthdate, gender, address, phone, email) VALUES (3, 'Bassam', 'Jebara', 'Gebran', '1994-07-11T21:32:29', 'M', 'Akkar', '03427753', 'bassam_gebran@yahoo.com');
INSERT INTO TBL_PROFILE(id, first_name, middle_name, last_name, birthdate, gender, address, phone, email) VALUES (4, 'Ziad', 'Issam', 'Toufic', '1998-05-24T21:32:29', 'M', 'Jnoub', '034277561', 'Toufic12453@live.com');
INSERT INTO TBL_PROFILE(id, first_name, middle_name, last_name, birthdate, gender, address, phone, email) VALUES (5, 'Hanna', 'Hasrouny', 'Abded', '1991-11-22T21:32:29', 'M', 'Saida', '034875880', 'Hannaabded@mail.com');

INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(1, 1, 2, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(2, 1, 1, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(3, 1, 1, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(4, 1, 2, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(5, 1, 3, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(6, 2, 4, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(7, 2, 1, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(8, 2, 2, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(9, 3, 2, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(10, 3, 1, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(11, 4, 1, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(12, 5, 4, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(13, 5, 4, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(14, 5, 4, '', '');
INSERT INTO TBL_HISTORY(id, profile_id, admission_id, description, result) VALUES(15, 5, 1, '', '');